/* Copyright (c) 2013-2015 Jeffrey Pfau
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
#pragma once

#include <QByteArray>
#include <QDateTime>
#include <QList>
#include <QString>
#include <QVariantMap>

namespace QGBA {
namespace Netplay {

// Generic lifecycle for a multiplayer session transport.
//
// This is intentionally independent of GBASIODriver and emulator internals.
// The module is intended to back MultiplayerController as an alternative to
// local-only lockstep.
enum class SessionState {
	Disconnected,
	Connecting,
	Connected,
	InRoom,
	Error,
};

enum class SessionEventType {
	LinkInput,
	LinkControl,
	Heartbeat,
	Custom,
};

enum class NetplayErrorCategory {
	ConnectionFailure,
	ProtocolMismatch,
	HeartbeatTimeout,
	RoomRejectedOrFull,
	MalformedMessage,
};

enum class NetplayFailureLayer {
	TransportSession,
	BackendAdapter,
	ControllerIntegration,
};

static inline const char* netplayErrorCategoryName(NetplayErrorCategory category) {
	switch (category) {
	case NetplayErrorCategory::ConnectionFailure:
		return "connection_failure";
	case NetplayErrorCategory::ProtocolMismatch:
		return "protocol_mismatch";
	case NetplayErrorCategory::HeartbeatTimeout:
		return "heartbeat_timeout";
	case NetplayErrorCategory::RoomRejectedOrFull:
		return "room_rejected_or_full";
	case NetplayErrorCategory::MalformedMessage:
		return "malformed_message";
	}
	return "unknown";
}

static inline const char* netplayFailureLayerName(NetplayFailureLayer layer) {
	switch (layer) {
	case NetplayFailureLayer::TransportSession:
		return "transport_session";
	case NetplayFailureLayer::BackendAdapter:
		return "backend_adapter";
	case NetplayFailureLayer::ControllerIntegration:
		return "controller_integration";
	}
	return "unknown";
}

struct SessionPeer {
	QString peerId;
	QString displayName;
	bool isLocal = false;
};

struct SessionRoom {
	QString roomId;
	QString roomName;
	int maxPeers = 0;
	QList<SessionPeer> peers;
};

// Transport-independent envelope for deterministic ordering of link events.
//
// The fields in this envelope are required regardless of the underlying
// transport (WebSocket, UDP relay, etc.) so that different backends can still
// produce the same simulation order.
struct LinkEventEnvelope {
	// Monotonic, per-sender sequence number assigned by the sender.
	//
	// Resets to 0 when a client establishes a new connection to the server.
	// It does not reset on room changes within the same transport connection.
	qint64 sequence = 0;

	// Server-authoritative numeric player ID of the sender for room-scoped
	// ordering/ownership checks. Assigned by the server when joining a room.
	int senderPlayerId = -1;

	// Logical simulation marker (tick/cycle/frame) chosen by the link layer.
	// Required for deterministic ordering across peers and transport backends.
	qint64 tickMarker = 0;

	// Opaque serialized link payload bytes.
	QByteArray payload;
};

enum class ClientIntentKind {
	CreateRoom,
	JoinRoom,
	LeaveRoom,
	Heartbeat,
	PublishLinkEvent,
};

struct ClientCreateRoomIntent {
	QString roomName;
	int maxPlayers = 0;
};

struct ClientJoinRoomIntent {
	// Server-authoritative room ID returned by room discovery/creation.
	QString roomId;
};

struct ClientLeaveRoomIntent {
	// Server-authoritative room ID for the room being left.
	QString roomId;
};

struct ClientHeartbeatIntent {
	// Monotonic, per-connection heartbeat counter generated by the client.
	// Resets to 0 whenever the transport connection is re-established.
	qint64 heartbeatCounter = 0;
};

struct ClientPublishLinkEventIntent {
	LinkEventEnvelope event;
};

enum class DisconnectReason {
	None,
	ClientRequested,
	ServerShutdown,
	NetworkTimeout,
	ProtocolError,
	RoomClosed,
	Kicked,
	Unknown,
};

enum class ServerEventKind {
	RoomJoined,
	PlayerAssigned,
	PeerJoined,
	PeerLeft,
	InboundLinkEvent,
	Error,
	Disconnected,
};

struct ServerRoomJoinedEvent {
	// Server-authoritative room ID.
	QString roomId;
	QString roomName;
	int maxPlayers = 0;
};

struct ServerPlayerAssignedEvent {
	// Server-authoritative player ID for this connection within the room.
	int playerId = -1;
};

struct ServerPeerJoinedEvent {
	// Server-authoritative player ID for the peer that joined.
	int playerId = -1;
	QString displayName;
};

struct ServerPeerLeftEvent {
	// Server-authoritative player ID for the peer that left.
	int playerId = -1;
	DisconnectReason reason = DisconnectReason::Unknown;
};

struct ServerInboundLinkEvent {
	LinkEventEnvelope event;
};

struct ServerErrorEvent {
	int code = 0;
	QString message;
};

struct ServerDisconnectedEvent {
	DisconnectReason reason = DisconnectReason::Unknown;
	QString message;
};

// Envelope for synchronized link/session events.
//
// The payload is opaque to this API. Higher-level systems can serialize any
// protocol-specific data and pass it through this envelope.
struct SessionEventEnvelope {
	QString eventId;
	QString sourcePeerId;
	qint64 sequence = 0;
	SessionEventType type = SessionEventType::Custom;
	QByteArray payload;
	QDateTime sentAtUtc;
	QVariantMap metadata;
};

struct SessionProtocolError {
	int code = 0;
	QString message;
	NetplayErrorCategory category = NetplayErrorCategory::ProtocolMismatch;
	NetplayFailureLayer layer = NetplayFailureLayer::TransportSession;
	QString endpoint;
	QString roomId;
	qint64 sequence = -1;
	qint64 expectedSequence = -1;
	QVariantMap details;
};

} // namespace Netplay
} // namespace QGBA
